spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(d9iJ+2Jh9ZEs9/YusjlK4mJJ/24LZ//M9HlJxCOBoK2cOA4vXJgPBZZXMF5KCqAgwcgg5+FZ5XxvO2G2tbCoGEIDT+RnOsEtXE7IJOX198bII7ZkOn0au4l/bLVuwYl8)
    username: ENC(05YNRyPs0WNUjs7uns8d9w==)
    password: ENC(L9CnTseQNs6ikvR+CDnyn0R/gVw0z4Wu)

  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false


mybatis:
  mapper-locations: mapper/*.xml