spring:
  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
      path: /h2-console  # 콘솔의 경로

  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:~/test;  #접속 URL
    username: EMC(zJDHU1kXsxfW5cbFROldhw==)  # 사용자 이름 (로그인 시 사용)
    password: ENC(J+3cEW59L42IMjAQk4TIMg==)  # 사용자 암호 (로그인 시 사용)

  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

kakao:
  client-id: ENC(9xO48MdiIscs7LfmQ2WKq7oVEDTPlAjFuhLyS6/jbOkowZ08LFbvvB4O28nFdTvS)
  redirect-uri: ENC(aRZHeZXKYZUNEMM9cjGo6bOmTly7W7eYPu9aIXIR5BF1YzeI0Aqt4pMlX+Kq87QqAWutR4344l8=)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor