spring:

  # DB 설정
  datasource:
    mariadb:
      driver-class-name: org.mariadb.jdbc.Driver
      url: ENC(d9iJ+2Jh9ZEs9/YusjlK4mJJ/24LZ//M9HlJxCOBoK2cOA4vXJgPBZZXMF5KCqAgwcgg5+FZ5XxvO2G2tbCoGEIDT+RnOsEtXE7IJOX198bII7ZkOn0au4l/bLVuwYl8)
      username: ENC(05YNRyPs0WNUjs7uns8d9w==)
      password: ENC(L9CnTseQNs6ikvR+CDnyn0R/gVw0z4Wu)

    h2:
      driver-class-name: org.h2.Driver  #h2 드라이버 설정
      url: jdbc:h2:~/test  #접속 URL
      username: ENC(zJDHU1kXsxfW5cbFROldhw==) # 사용자 이름 (로그인 시 사용)
      password: ENC(YCpqImgdltL2qKQ/R62LPg==) # 사용자

    h2:
      console:
        enabled: true
        path: /h2-console

    devtools:
      livereload:
        enabled: true
    freemarker:
      cache: false

  # 마이바티스 설정
  mybatis:
    mapper-locations: mapper/*.xml

  # 이메일 인증
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(eQPUp6+s9q+72FWQnWKTQH75B3/oXcOATMdmxF9U1bI=)
    password: ENC(Jp0luySRt0Kx4Z7WB4dqSeJdHRybGiiN)
    protocol: smtp
    properties:
      mail:
        debug: true
        transport:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            enable: true
            trust: smtp.gmail.com

  # Swagger pattern setting
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# Jasypt 설정
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

# 카카오 로그인 설정
kakao:
  client-id: ENC(9xO48MdiIscs7LfmQ2WKq7oVEDTPlAjFuhLyS6/jbOkowZ08LFbvvB4O28nFdTvS)
  redirect-uri: ENC(KqZ+WOF1JVUjCyffaQKIRYeoNT/R0YefTmnoWsF/GllxGqK+KbeEumtHHMci+9nE)