spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(eQPUp6+s9q+72FWQnWKTQH75B3/oXcOATMdmxF9U1bI=)
    password: ENC(Jp0luySRt0Kx4Z7WB4dqSeJdHRybGiiN)
    protocol: smtp
    properties:
      mail:
        debug: true
        transport:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
