spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: ENC(3CwulSSL5Im68Bi4y2S8XN92dvSgi3L8)
    password: ENC(s//SJX7k+7a+utjhuKaV9KXYEKrwYuAy)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            enable: true
            trust: smtp.naver.com