# Repo Action 페이지에 나타날 이름
name: Spring Boot & Gradle CI/CD

# Event Trigger
on:
  push: # main과 develop 브랜치에서 push가 일어났을 때 github action 동작
    branches:
      - main
      - develop
  pull_request: # feature/*와 develop 브랜치에서 PR이 일어났을 때 github action 동작
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경 지정
    steps:
      - uses: actions/checkout@v2 # github action 버전 지정(major version)

      - name: Set up JDK 11 # JAVA 버전 지정
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      # 실제 application build
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

#      # test application build
#      - name: Test with Gradle
#        run: ./gradlew test
#
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          file: ./build/reports/jacoco/test/jacocoTestReport.xml
#
#      # test 후 result를 보기 위해 추가
#      - name: Publish Unit Test Results
#        uses: EnricoMi/publish-unit-test-result-action@v1
#        if: ${{ always() }} # test가 실패해도 report를 남기기 위해 설정
#        with:
#          files: build/test-results/**/*.xml

        # 새로 추가 된 부분
        - name: Make zip file
          run: zip -r ./$GITHUB_SHA.zip .
          shell: bash

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS-REGION: ${{ secrets.AWS_REGION }}

        - name: Upload to S3
          run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip